import React, { useEffect, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { ArrowLeft, ArrowUpLeft, Check, ChevronDown, ChevronLeft, CircleCheck, Menu, X, Sparkles, Gauge, ShoppingBag, Truck, BarChart3, MessageCircle, ArrowUpRight } from 'lucide-react';
import './styles.css';

const sitePackages = [
  { id:'launch-lite', platform:'Launch', name:'Launch Lite', price:10500, label:'للبداية المركزة', featured:false, items:['حتى ٤ صفحات أساسية','حتى ٣٠ منتجًا عند التسليم','قالب RTL مستجيب وتخصيص هوية','دفع وشحن أساسي + WhatsApp CTA','QA وتسليم وجلسة تدريب'] },
  { id:'commerce-launch', platform:'Commerce', name:'Commerce Launch', price:22500, label:'الأكثر مناسبة', featured:true, items:['حتى ٨ صفحات و١٠٠ منتج','تخصيص UI حقيقي للبراند','Cart وCheckout وCOD','حتى تكاملين دفع/شحن جاهزين','Tracking وCSV import وتدريبان'] },
  { id:'growth-loop', platform:'Growth', name:'Growth Loop', price:7000, label:'شهري بعد الإطلاق', featured:false, items:['تحسين Conversion وCheckout','Merchandising وعروض المنتجات','مراجعة COD والسلة المتروكة','تقرير وDashboard مبدئي','اجتماع شهري ودعم أولوية'] }
];

const marketingAddons = [
  { id:'media', name:'Media Buying', price:0, note:'إدارة الحملات والإعلانات — تسعير حسب الميزانية والنطاق' },
  { id:'content', name:'Social & Content', price:0, note:'خطة محتوى وإدارة شهرية — تسعير حسب عدد القنوات والمخرجات' },
  { id:'creative', name:'Creative & Design', price:0, note:'تصميمات إعلانات ومواد بيع — تسعير حسب عدد الـAssets' },
  { id:'tracking', name:'Tracking & Analytics', price:2500, note:'إعداد Events وGA4 وPixels وDashboard مبدئي' },
  { id:'cro', name:'CRO & Checkout Fixes', price:3500, note:'مراجعة وتحسين رحلة التحويل والـCheckout' },
  { id:'photo', name:'Product Photography', price:0, note:'تصوير المنتجات — تسعير حسب العدد والموقع' }
];
const SITE_URL = 'https://cartmakers.com';

const projects = [
  {slug:'eg-moms-recipes',title:"Eg Mom's Recipes",category:'Editorial / Food Blog',tag:'مجلة وصفات مصرية',image:'/portfolio/eg-moms-recipes.webp',url:'https://egmomrecipes.unaux.com/?i=1',summary:'تجربة Editorial تحمل قصة أكل بيتي مصري وتحوّلها إلى وصفات وتصنيفات قابلة للاكتشاف.',brief:'مدونة أكل تعتمد على الهوية والثقافة قبل الوصفة: قصة، أطباق مميزة، Blog، وتصنيفات واضحة للتصفح.',insight:'القيمة ليست في الوصفة وحدها؛ في الإحساس بالبيت والذاكرة الذي يجعل القارئ يريد العودة.',features:['Hero قصصي','Signature dishes','Blog وتصنيفات وصفات','هوية مصرية دافئة']},
  {slug:'vervac',title:'Vervac Animal Care',category:'E-commerce / Animal Care',tag:'رعاية الحيوانات في الخليج',image:'/portfolio/vervac.webp',url:'https://vervac.com/',summary:'علامة بحرينية تجمع المنتجات، قصة العلامة، وتصنيفات العناية بالحيوانات داخل تجربة متجر واسعة.',brief:'موقع Animal Care يربط بين Shop وPortfolio categories وقصة الشركة والمقالات التعليمية، مع مسارات واضحة للشراء.',insight:'المحتوى التعليمي وقصة العلامة يرفعان الثقة في فئة تحتاج شرحًا قبل اختيار المنتج.',features:['Product category portfolio','Brand story sections','Shop وAccount وCart','Blog وInformation Academy']},
  {slug:'velora',title:'Velora Flowers',category:'E-commerce / Flowers',tag:'متجر زهور ومناسبات',image:'/portfolio/velora.webp',url:'https://velora-eg.online/',summary:'متجر زهور يضع المناسبات والتوصيل وتجربة الهدية في مقدمة الرحلة.',brief:'تجربة متجر WooCommerce-style للزهور، تبدأ من Hero عاطفي ثم Shop by Occasion، المنتجات، والـCart.',insight:'التقسيم حسب المناسبة يبيع السياق قبل المنتج، وهو مدخل مناسب لطلبات الهدايا.',features:['Occasion-led merchandising','Fresh flowers positioning','EGP cart flow','Shop وWishlist']},
  {slug:'pharaohs-stone',title:'Pharaohs Stone',category:'Corporate / Construction',tag:'مقاولات الحجر والدبش',image:'/portfolio/pharaohs-stone.webp',url:'https://pharaohsstone.com/',summary:'موقع شركة مقاولات عربية يشرح تخصصات الحجر والدبش ويعرض نماذج من المشاريع.',brief:'موقع Corporate يعتمد على Hero قوي، تقسيم الخدمات، نبذة عن الشركة، ومشاريع سابقة تقود إلى طلب التسعيرة.',insight:'ترتيب الخدمات والمشاريع حول الثقة يجعل الخدمة الإنشائية الملموسة مفهومة حتى قبل المكالمة.',features:['Arabic RTL corporate site','Services taxonomy','Project showcase','Quote وWhatsApp CTAs']},
  {slug:'islamisch-akademisch',title:'Islamisch Akademisch',category:'Education / Quran Academy',tag:'Premium Online Quran Academy',image:'/portfolio/islamisch-akademisch.webp',url:'https://islamisch-akademisch.com',summary:'أكاديمية ألمانية اللغة للتعلم الفردي في القرآن والتجويد والدراسات الإسلامية مع حصة تجريبية مجانية.',brief:'Landing Page عالية الوضوح تستهدف الأهالي والبالغين، وتجمع البرامج، المعلمين، الـFAQ، ونموذج تقييم مجاني في مسار واحد.',insight:'الـLead Form هنا جزء من المنتج نفسه: يجمع بيانات الطالب والبرنامج واللغة قبل بداية المحادثة.',features:['German-first experience','Five learning programs','Free assessment CTA','Teacher matching وLead form']},
  {slug:'ufuqar',title:'Ufuqar News Magazine',category:'Editorial / Arabic News',tag:'مجلة إخبارية عربية',image:'/portfolio/ufuqar.webp',url:'https://ufuqar.com/',summary:'بوابة أخبار عربية تعتمد على الأخبار العاجلة، الأقسام المتعددة، وواجهة كثيفة للمحتوى اليومي.',brief:'موقع Editorial RTL يجمع الأخبار الرائجة، الأقسام، المقالات، أسعار الذهب والفضة، وروابط السياسات في تجربة واحدة.',insight:'في المواقع الإخبارية، التحدي ليس إضافة محتوى أكثر؛ بل ترتيب الأولويات حتى يعرف القارئ أين يبدأ وما الذي يتابع.',features:['RTL editorial structure','Trending news strip','تصنيفات متعددة','Gold & Silver tables']},
  {slug:'selim-marketing',title:'Selim Marketing',category:'Marketing Services / E-commerce',tag:'متجر خدمات تسويق',image:'/portfolio/selim-marketing.webp',url:'https://selimmarketing.com',summary:'متجر عربي للخدمات التسويقية يقسم العرض حسب المنصة ويقرب الخدمة من قرار الشراء.',brief:'واجهة Commerce لخدمات السوشيال والتصميم والمونتاج، مع تصنيفات حسب المنصة، عروض، Cart، وحسابات العملاء.',insight:'فصل الخدمات حسب المنصة يحوّل عرضًا واسعًا مثل Social Marketing إلى اختيارات قابلة للفهم والشراء.',features:['Arabic RTL storefront','Platform-based categories','Offers وProduct cards','Cart وWishlist وAccount']},
  {slug:'9ten',title:'9TEN Store',category:'E-commerce / Footwear',tag:'متجر أحذية عربي',image:'/portfolio/9ten.webp',url:'https://9tenstore-eg.com',summary:'متجر RTL للأحذية يقسم التجربة إلى رجالي ونسائي ويقود إلى المنتجات الجديدة.',brief:'واجهة عربية مباشرة تضع التصنيفات والمنتجات والعروض في مركز التجربة، مع قنوات تواصل وسياسات واضحة.',insight:'التصنيف البسيط—رجالي/نسائي—يختصر أول قرار للزائر ويترك له مساحة لاستكشاف المنتج.',features:['RTL navigation','Men / Women taxonomy','Sale pricing','سياسات واستبدال وتواصل']},
  {slug:'black-horses',title:'Black Horses',category:'Corporate / Engineering',tag:'موقع شركة هندسية',image:'/portfolio/black-horses.webp',url:'https://blackhorses.sa/',summary:'تجربة Corporate تقود الزائر من الوعد الهندسي إلى الخدمات والمشاريع المميزة.',brief:'موقع شركة مقاولات وهندسة يعتمد على Hero بصري قوي، تقسيم خدمات واضح، ومشاريع حقيقية كمدخل للثقة.',insight:'المشروع يوضح كيف تجعل صور المشاريع والبنية المعلوماتية شركة خدمات تبدو ملموسة وقابلة للتصديق.',features:['Hero بصري قوي','Featured Projects','خدمات هندسية مصنفة','صفحة Portfolio مستقلة']},
  {slug:'sandy-collection',title:'Sandy Collection',category:'E-commerce / Jewelry',tag:'متجر مجوهرات',image:'/portfolio/sandy-collection.webp',url:'https://sandy-collection.com',summary:'واجهة متجر مجوهرات تعتمد على الصورة، الكولكشن، والسعر لتقريب قرار الشراء.',brief:'متجر D2C يعرض الكولكشن والـBest Sellers مع Wishlist وQuick View وCart لتقليل المسافة بين الإعجاب والشراء.',insight:'عندما يكون المنتج بصريًا، ترتيب الصور والكولكشن أهم من كثرة الكلام—وهو ما يظهر في التجربة.',features:['Merchandising بصري','Product cards مع أسعار وعروض','Cart وWishlist','Shop وCategories']},
  {slug:'la-maison-francaise',title:'La Maison Française',category:'Education / Landing Page',tag:'أكاديمية لغة',image:'/portfolio/la-maison-francaise.webp',url:'https://lamaisonfrançaise.com',summary:'Landing Page موجهة للأهل تشرح التعلم، المتابعة، والخطوة الأولى لحجز حصة تجريبية.',brief:'تجربة تعليمية تستهدف أولياء الأمور برسالة محددة، CTA للحصة المجانية، ومحتوى يشرح البرامج والفئات العمرية.',insight:'الـLanding الجيد لا يبيع الحصة فقط؛ يزيل قلق ولي الأمر حول المتابعة، المستوى، وطريقة التعلم.',features:['Audience واضح: الأطفال والأهل','Free-trial CTA','شرح البرامج والمراحل','تواصل مباشر عبر WhatsApp']},
  {slug:'opreva',title:'OPREVA',category:'E-commerce / Skincare',tag:'متجر عناية بالبشرة',image:'/portfolio/opreva.webp',url:'https://opreva-eg.com/',summary:'متجر Skincare يربط الـProduct Merchandising بالمكونات والفئات والعروض.',brief:'واجهة تعرض المنتجات والعروض، ثم تساعد الزائر على فهم الفئات والمكونات قبل الوصول إلى الشراء.',insight:'شرح المكوّن بجانب المنتج يقلل الحيرة ويحوّل لغة skincare المعقدة إلى قرار أبسط.',features:['Sale merchandising','Categories: Face / Body / Hair','Ingredient-led sections','Cart وWishlist']},
  {slug:'ms-uniforms',title:'MS Uniforms',category:'E-commerce / Fashion',tag:'متجر يونيفورم طبي',image:'/portfolio/ms-uniforms.webp',url:'https://ms-uniforms.com/',summary:'تجربة Catalog لمنتجات طبية تعتمد على المقاسات، الألوان، والتصنيفات.',brief:'متجر يقدّم ملابس طبية كمنتج Fashion/Utility مع خيارات مقاسات وألوان ومسارات Shop واضحة.',insight:'في المنتجات القابلة للتنوع، UX الاختيار—المقاس واللون والنوع—جزء من البيع نفسه.',features:['Categories واضحة','Sizes وColors','Product options','Shop وCart']},
  {slug:'quran-academy',title:'Quran Academy',category:'Education / Landing Page',tag:'أكاديمية تعليم أونلاين',image:'/portfolio/quran-academy.webp',url:'https://quranacademyy.com/',summary:'Landing Page طويلة تشرح البرامج التعليمية وتضع التسجيل في مقدمة الرحلة.',brief:'موقع تعليمي يشرح البرامج والفئات، يدعم الثقة بالمحتوى، ويكرر CTA التسجيل في نقاط مناسبة.',insight:'الخدمات التعليمية تحتاج شرحًا وطمأنة قبل الـCTA؛ المحتوى هنا يقوم بدور المبيعات والتعريف معًا.',features:['Hero + Enroll CTA','برامج مصنفة','تعريف بالخدمات','محتوى طويل يدعم القرار']},
  {slug:'shopping-online-store',title:'Shopping Online Store',category:'E-commerce / Outdoor',tag:'معدات تخييم ومغامرات',image:'/portfolio/shopping-online-store.webp',url:'https://shopping-online-store.com/',summary:'متجر عربي لمعدات التخييم والمغامرات يعرض المنتجات والأسعار ومحتوى يساعد على الاختيار.',brief:'واجهة Commerce تجمع Hero للمغامرة، Catalog بمنتجات EGP، Blog، وتواصل، مع تنبيه واضح أن النسخة الحالية Test Store.',insight:'الـContent هنا ليس إضافة جانبية؛ مقالات التخييم تساعد الزائر على فهم المنتج قبل إضافته للسلة.',features:['Arabic storefront','Outdoor product catalog','EGP pricing','Blog + shop journey']},
];


const diagnosticQuestions = [
  { id:'channel', label:'أغلب الطلب بيجيلك منين؟', options:[['social','Instagram / WhatsApp'],['marketplace','Marketplace'],['store','متجر موجود'],['mixed','أكثر من قناة']] },
  { id:'stage', label:'أنت في أي مرحلة؟', options:[['new','لسه هنبدأ'],['leaking','عندي طلب والرحلة بتسرّب'],['scaling','عندي متجر وعايز أكبر'],['rebuild','عايز أعيد البناء']] },
  { id:'catalog', label:'حجم الكتالوج تقريبًا؟', options:[['small','أقل من ٣٠ منتج'],['medium','٣٠–١٥٠ منتج'],['large','أكثر من ١٥٠ منتج']] },
  { id:'pain', label:'أكبر مشكلة دلوقتي؟', options:[['checkout','Checkout / دفع / COD'],['catalog','ترتيب المنتجات والمحتوى'],['tracking','Tracking وقياس'],['launch','إطلاق متجر من الصفر']] }
];
function CommerceDiagnostic({onComplete}){
  const [step,setStep]=useState(0),[answers,setAnswers]=useState({}),[result,setResult]=useState(null);
  const answer=(id,value)=>{const next={...answers,[id]:value};setAnswers(next);if(step<diagnosticQuestions.length-1)setStep(step+1);else{const recommendation=next.stage==='new'?'Launch Lite':next.stage==='scaling'?'Growth Loop':next.pain==='checkout'?'Commerce Launch':'Commerce Diagnostic';const insight=next.pain==='checkout'?'أكبر فرصة عندك غالبًا في تقليل الاحتكاك بين المنتج والدفع.':next.pain==='tracking'?'قبل أي إنفاق إضافي، ثبّت القياس واعرف أين تتسرب الطلبات.':next.channel==='social'?'نحتاج نحول الطلب المتناثر من السوشيال إلى قناة مملوكة قابلة للقياس.':'نبدأ من ترتيب الرحلة والكتالوج قبل ما نكبر التنفيذ.';const value={recommendation,insight,answers:next};setResult(value);onComplete?.(value)}};
  if(result)return <div className="diagnostic-result"><div className="result-signal"><Sparkles size={20}/> قراءة أولية</div><h3>الخطوة الأقرب لحالتك: <em>{result.recommendation}</em></h3><p>{result.insight}</p><a className="button primary" href="#contact">كمّل بالـBrief <ArrowLeft size={17}/></a><button className="diagnostic-reset" onClick={()=>{setStep(0);setAnswers({});setResult(null)}}>ابدأ من جديد</button></div>;
  const q=diagnosticQuestions[step];
  return <div className="diagnostic-card"><div className="diagnostic-top"><span>COMMERCE DIAGNOSTIC</span><b>0{step+1} / 0{diagnosticQuestions.length}</b></div><div className="diagnostic-progress"><span style={{width:`${((step+1)/diagnosticQuestions.length)*100}%`}}/></div><h3>{q.label}</h3><div className="diagnostic-options">{q.options.map(([value,label])=><button key={value} onClick={()=>answer(q.id,value)}>{label}<ArrowLeft size={16}/></button>)}</div><small>إجابة سريعة — مفيش إجابة غلط.</small></div>;
}
function EnglishPage(){
  return <div className="english-page"><header className="nav shell"><a className="brand" href="/"><img className="brand-logo" src="/assets/cartmakers-primary-light.svg" alt="CartMakers — Ecommerce Systems & Growth"/></a><a className="nav-cta" href="/#contact">Start a project <ArrowUpRight size={16}/></a></header><main><section className="english-hero shell"><div className="section-kicker lime">EGYPT-FIRST / GCC-READY</div><h1>We build<br/><em>stores that work.</em></h1><p>CartMakers helps growing brands turn scattered demand into a commerce system that converts, tracks, and keeps improving.</p><div className="hero-actions"><a className="button primary" href="/#contact">Book a Commerce Diagnostic <ArrowUpRight size={17}/></a><a className="text-link" href="/">العربية <ArrowLeft size={16}/></a></div></section><section className="section shell english-grid"><div><div className="section-kicker">THE SYSTEM</div><h2>From social demand<br/>to <em>repeat purchase.</em></h2></div><div className="english-points"><div><ShoppingBag size={20}/><b>Storefront & Catalog</b><span>Clear product paths that make choice easier.</span></div><div><Gauge size={20}/><b>Checkout & COD</b><span>Less doubt between cart and confirmation.</span></div><div><BarChart3 size={20}/><b>Tracking & Growth</b><span>Baselines, events, and practical next moves.</span></div></div></section><section className="section english-cta shell"><div><div className="section-kicker">NO GENERIC PROPOSALS</div><h2>Find the leak<br/><em>before you rebuild.</em></h2></div><a className="button primary" href="/#contact">Start with the Brief <ArrowUpRight size={17}/></a></section></main></div>;
}

function ProjectPage({project}){
  if(!project) return <><header className="nav shell"><a className="brand" href="/"><img className="brand-logo" src="/assets/cartmakers-primary-light.svg" alt="CartMakers — Ecommerce Systems & Growth"/></a></header><main className="project-not-found shell"><h1>المشروع غير موجود.</h1><a className="button primary" href="/#portfolio">ارجع للبورتفوليو <ArrowLeft size={18}/></a></main></>;
  return <div dir="rtl"><header className="nav shell"><a className="brand" href="/"><img className="brand-logo" src="/assets/cartmakers-primary-light.svg" alt="CartMakers — Ecommerce Systems & Growth"/></a><a className="nav-cta" href="/#portfolio">كل الأعمال <ArrowLeft size={16}/></a></header><main className="project-page"><section className="project-hero shell"><div><div className="section-kicker">{project.category}</div><h1>{project.title}<br/><em>{project.tag}</em></h1><p>{project.summary}</p><a className="button primary" href={project.url} target="_blank" rel="noreferrer">شاهد الموقع الأصلي <ArrowLeft size={18}/></a></div><div className="project-visual"><img src={project.image} alt={project.title}/><span>LIVE REFERENCE / {project.slug.toUpperCase()}</span></div></section><section className="project-detail shell"><div><div className="section-kicker">Brief المشروع</div><h2>الفكرة وراء<br/><em>التجربة.</em></h2></div><div><p className="project-brief">{project.brief}</p><p className="project-insight"><b>CartMakers takeaway</b>{project.insight}</p><div className="project-features">{project.features.map(f=><span key={f}><Check size={15}/>{f}</span>)}</div></div></section><section className="project-disclaimer"><div className="shell"><span><CircleCheck size={17}/> Reference case study</span><p>هذه الصفحة تعرض الموقع كمرجع بصري ومعلوماتي. لا ننسب نتائج، تقنيات، أو تنفيذًا لـCartMakers إلا إذا تم توثيقه بشكل منفصل.</p></div></section></main></div>;
}


function ProjectCard({project,index}){
  return <article className="portfolio-card" key={project.slug}><a className="portfolio-image" href={`/projects/${project.slug}`}><img src={project.image} alt={project.title}/><span>{String(index+1).padStart(2,'0')}</span></a><div className="portfolio-card-copy"><div><small>{project.category}</small><h3>{project.title}</h3></div><a href={`/projects/${project.slug}`} aria-label={`افتح مشروع ${project.title}`}><ArrowUpLeft size={22}/></a><p>{project.summary}</p></div></article>;
}

function PortfolioSlider({compact=false}){
  const [active,setActive]=useState(0);
  const go=(step)=>setActive(current=>(current+step+projects.length)%projects.length);
  const current=projects[active];
  const next=projects[(active+1)%projects.length];
  const previous=projects[(active-1+projects.length)%projects.length];
  return <div className={compact?'portfolio-slider compact':'portfolio-slider'} dir="rtl">
    <div className="slider-stage">
      <article className="slider-main">
        <a className="slider-main-image" href={`/projects/${current.slug}`}><img src={current.image} alt={current.title}/><span>{String(active+1).padStart(2,'0')} / {String(projects.length).padStart(2,'0')}</span></a>
        <div className="slider-main-copy"><div><small>{current.category}</small><h3>{current.title}</h3><p>{current.summary}</p></div><a className="button primary" href={`/projects/${current.slug}`}>شوف المشروع <ArrowLeft size={17}/></a></div>
      </article>
      <a className="slider-preview preview-next" href={`/projects/${next.slug}`}><img src={next.image} alt={next.title}/><div><small>التالي</small><strong>{next.title}</strong></div></a>
      {!compact&&<a className="slider-preview preview-previous" href={`/projects/${previous.slug}`}><img src={previous.image} alt={previous.title}/><div><small>السابق</small><strong>{previous.title}</strong></div></a>}
    </div>
    <div className="slider-controls"><div className="slider-progress"><span style={{width:`${((active+1)/projects.length)*100}%`}}/></div><div className="slider-buttons"><button type="button" onClick={()=>go(-1)} aria-label="المشروع السابق">السابق <ChevronLeft size={17}/></button><button type="button" onClick={()=>go(1)} aria-label="المشروع التالي">التالي <ArrowLeft size={17}/></button></div></div>
  </div>;
}

function PortfolioPage(){
  const [filter,setFilter]=useState('all');
  const filters=[['all','كل الأعمال'],['E-commerce','E-commerce'],['Corporate','Corporate'],['Education','Education'],['Editorial','Editorial']];
  const visibleProjects=filter==='all'?projects:projects.filter(p=>p.category.startsWith(filter));
  return <div dir="rtl"><header className="nav shell"><a className="brand" href="/"><img className="brand-logo" src="/assets/cartmakers-primary-light.svg" alt="CartMakers — Ecommerce Systems & Growth"/></a><a className="nav-cta" href="/#contact">ابدأ مشروعك <ArrowLeft size={16}/></a></header><main className="portfolio-page"><section className="portfolio-page-hero shell"><div className="section-kicker lime">THE WORK / CARTMAKERS</div><h1>أعمالنا<br/><em>تتحرك قدامك.</em></h1><p>مجموعة من المواقع والمتاجر والـLanding Pages التي نستخدمها كمرجع بصري لفهم طريقة بناء تجربة أوضح.</p></section><section className="shell portfolio-featured"><div className="section-head"><div><div className="section-kicker">Interactive archive</div><h2>اختار مشروع،<br/>وشوف <em>التجربة.</em></h2></div><p>حرّك السلايدر أو افتح أي مشروع لتشوف الـBrief، الفكرة، وأهم قرارات التجربة.</p></div><PortfolioSlider/></section><section className="shell portfolio-library"><div className="section-head"><div><div className="section-kicker">All selected work</div><h2>كل المشاريع<br/><em>في مكان واحد.</em></h2></div><p>{projects.length} مشروعًا في Ecommerce وCorporate وEducation وEditorial.</p></div><div className="portfolio-filters">{filters.map(([value,label])=><button key={value} className={filter===value?'active':''} onClick={()=>setFilter(value)}>{label}</button>)}</div><div className="portfolio-grid">{visibleProjects.map((project,index)=><ProjectCard project={project} index={index} key={project.slug}/>)}</div></section></main></div>;
}

const services = [
  ['الموقع أو المتجر', 'مش صفحة شكلها حلو وخلاص. نبني قناة مملوكة تفهم المنتج، العميل، الدفع، والشحن.', '01'],
  ['الدفع والتشغيل', 'نرتب الـCheckout والـCOD والتأكيد والتوصيل والمرتجعات بحيث الطلب لا يضيع بعد الضغط على زر الشراء.', '02'],
  ['التتبع والنمو', 'نثبت Baseline ونربط Analytics وCRM والتحسينات عشان تعرف أين تكسب وأين تخسر.', '03']
];
const process = [['01','نفهم','نبدأ من طريقة البيع والطلب الموجود، مش من اختيار Theme.'],['02','نرتب','نحدد أين التسريب، وما الذي يستحق التنفيذ أولًا.'],['03','نبني','ننفذ المتجر والتكاملات والتتبع بنطاق واضح.'],['04','نكبّر','نحوّل البيانات إلى تحسينات وRetention ونمو مستمر.']];
const faqs = [['هل أنتم شركة تصميم مواقع؟','نحن نبني مواقع ومتاجر، لكننا لا نبيع تصميمًا منفصلًا عن التجارة. الموقع عندنا جزء من نظام يشمل الـCheckout والدفع والتوصيل والتتبع والنمو.'],['هل تعملون على Shopify فقط؟','لا. نختار WordPress/WooCommerce أو Shopify أو Zid أو غيرها حسب طريقة التشغيل والدفع والاحتياج المثبت، وليس حسب تفضيل تقني مسبق.'],['هل الأسعار نهائية؟','الأسعار المعروضة Starting From لتوضيح مستوى الاستثمار. السعر النهائي يتحدد بعد النطاق، عدد الصفحات والمنتجات، التكاملات، المحتوى، والـQA. رسوم المنصات والدفع والشحن والإعلانات منفصلة.'],['هل تضمنون المبيعات أو الـROAS؟','لا نبيع ضمانات وهمية. نضمن وضوح النطاق، القياس، والتنفيذ المنضبط. المبيعات تتأثر بالعرض والسعر والزيارات والتشغيل والسوق.'],['ماذا أحتاج قبل البدء؟','منتج أو خدمة واضحة، شخص صاحب قرار، محتوى وبيانات أساسية، وإمكانية توفير access واعتمادات في وقتها.']];

function setMeta(name, content, property=false){
  const selector=property?`meta[property="${name}"]`:`meta[name="${name}"]`;
  let node=document.head.querySelector(selector);
  if(!node){node=document.createElement('meta');node.setAttribute(property?'property':'name',name);document.head.appendChild(node)}
  node.setAttribute('content',content);
}
function updateSeo(projectSlug){
  const project=projects.find(p=>p.slug===projectSlug);
  const isPortfolio=window.location.pathname==='/portfolio';
  const isEnglish=window.location.pathname==='/en';
  const title=project?`${project.title} — CartMakers`:isEnglish?'CartMakers — Ecommerce Systems & Growth':isPortfolio?'أعمال CartMakers — Ecommerce Systems & Growth':'CartMakers — أنظمة تجارة تشتغل وتكبر';
  const description=project?`${project.summary} مرجع بصري ومعلوماتي من CartMakers.` :isEnglish?'CartMakers builds and improves ecommerce systems for growing brands.':'CartMakers بتبني وتصلّح وتكبّر أنظمة التجارة للبراندات اللي عندها طلب.';
  document.title=title;
  setMeta('description',description);
  setMeta('og:title',title,true);setMeta('og:description',description,true);setMeta('og:url',`${SITE_URL}${window.location.pathname}`,true);
  setMeta('twitter:title',title);setMeta('twitter:description',description);
  let canonical=document.head.querySelector('link[rel=canonical]');if(!canonical){canonical=document.createElement('link');canonical.rel='canonical';document.head.appendChild(canonical)}canonical.href=`${SITE_URL}${window.location.pathname}`;
  let schema=document.getElementById('cartmakers-schema');if(schema)schema.remove();
  const data=project?{'@context':'https://schema.org','@type':'CreativeWork','name':project.title,'description':project.summary,'url':`${SITE_URL}/projects/${project.slug}`}: {'@context':'https://schema.org','@type':'Organization','name':'CartMakers','description':description,'url':SITE_URL,'email':'hello@cartmakers.com'};
  schema=document.createElement('script');schema.id='cartmakers-schema';schema.type='application/ld+json';schema.textContent=JSON.stringify(data);document.head.appendChild(schema);
}

function App(){
  const [diagnosticResult,setDiagnosticResult]=useState(null);
  const projectSlug=window.location.pathname.match(/^\/projects\/([^/]+)/)?.[1];
  useEffect(()=>{updateSeo(projectSlug);const observer=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting)entry.target.classList.add('is-visible')}),{threshold:.12});document.querySelectorAll('.reveal').forEach(el=>observer.observe(el));return()=>observer.disconnect()},[projectSlug]);
  const [menu,setMenu]=useState(false),[openFaq,setOpenFaq]=useState(0),[sent,setSent]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState('');
  const [selectedSite,setSelectedSite]=useState('wp-7000');
  const [selectedAddons,setSelectedAddons]=useState([]);
  const selectedPackage=sitePackages.find(x=>x.id===selectedSite) || sitePackages[1];
  const total=selectedPackage.price+selectedAddons.reduce((sum,id)=>sum+(marketingAddons.find(x=>x.id===id)?.price||0),0);
  const toggleAddon=(id)=>setSelectedAddons(prev=>prev.includes(id)?prev.filter(x=>x!==id):[...prev,id]);
  async function submit(e){e.preventDefault();setBusy(true);setError('');const data=Object.fromEntries(new FormData(e.currentTarget));data.package={platform:selectedPackage.platform,name:selectedPackage.name,price:selectedPackage.price};data.addons=selectedAddons.map(id=>{const a=marketingAddons.find(x=>x.id===id);return {name:a.name,price:a.price,note:a.note}});data.estimated_total=total;data.diagnostic=diagnosticResult;try{const r=await fetch('/api/contact',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(data)});const j=await r.json();if(!r.ok||!j.ok)throw new Error(j.message||'حصلت مشكلة، حاول مرة أخرى.');setSent(true);e.currentTarget.reset()}catch(err){setError(err.message)}finally{setBusy(false)}}
  const closeMenu=()=>setMenu(false);
  if(window.location.pathname==='/en') return <EnglishPage />;
  if(projectSlug) return <ProjectPage project={projects.find(p=>p.slug===projectSlug)} />;
  if(window.location.pathname==='/portfolio') return <PortfolioPage />;
  return <div dir="rtl">
    <header className="nav shell"><a className="brand" href="#top" onClick={closeMenu}><img className="brand-logo" src="/assets/cartmakers-primary-light.svg" alt="CartMakers — Ecommerce Systems & Growth"/></a><button className="menu-toggle" onClick={()=>setMenu(!menu)} aria-label="القائمة">{menu?<X/>:<Menu/>}</button><nav className={menu?'nav-links open':'nav-links'}><a href="#services" onClick={closeMenu}>بنشتغل على إيه؟</a><a href="#packages" onClick={closeMenu}>الباقات</a><a href="/portfolio" onClick={closeMenu}>أعمالنا</a><a href="/en" onClick={closeMenu}>EN</a><a href="#process" onClick={closeMenu}>الطريقة</a><a className="nav-cta" href="#contact" onClick={closeMenu}>ابدأ من هنا <ArrowLeft size={16}/></a></nav></header>
    <main id="top">
      <section className="hero shell reveal"><div className="hero-copy"><div className="eyebrow">COMMERCE SYSTEMS <i/> GROWTH</div><h1>من أول <em>Click</em><br/>لحد Repeat<br/><em>Purchase.</em></h1><p className="lede">بنحوّل الطلب المتناثر من السوشيال والـMarketplace إلى نظام تجارة يبيع، يتتبع، ويتحسن — من غير وعود وهمية.</p><div className="hero-actions"><a className="button primary" href="#diagnostic">اعرف أكبر تسريب <ArrowLeft size={18}/></a><a className="text-link" href="#portfolio">شوف الـProof <ChevronLeft size={17}/></a></div><div className="proof"><CircleCheck size={18}/><span>Egypt-first. GCC-ready. مبنيين على تشغيل حقيقي.</span></div></div><div className="hero-panel hero-control-room"><div className="panel-label">COMMERCE CONTROL ROOM <span>LIVE FLOW</span></div><div className="control-metrics"><span><b>01</b><small>DEMAND</small><strong>Social</strong></span><span><b>02</b><small>CONVERSION</small><strong>Checkout</strong></span><span><b>03</b><small>OPERATIONS</small><strong>COD + Delivery</strong></span><span className="metric-active"><b>04</b><small>GROWTH</small><strong>Repeat</strong></span></div><div className="flow flow-enhanced"><div><b>01</b><span>طلب من السوشيال</span><small>attention</small></div><div><b>02</b><span>متجر وCheckout</span><small>conversion</small></div><div><b>03</b><span>دفع وCOD وتوصيل</span><small>operations</small></div><div><b>04</b><span>تتبع وبيانات</span><small>measurement</small></div><div className="active"><b>05</b><span>شراء متكرر</span><small>growth</small></div></div><div className="panel-foot"><span>كل خطوة لها تأثير.</span><span className="pulse"/></div></div></section>
      <section className="marquee"><div className="marquee-inner"><span>STORE</span><b>→</b><span>CHECKOUT</span><b>→</b><span>PAYMENT</span><b>→</b><span>DELIVERY</span><b>→</b><span>GROWTH</span><b>→</b><span>STORE</span></div></section><section className="proof-strip shell reveal"><div><span className="proof-icon"><ShoppingBag size={18}/></span><b>Storefront</b><small>عرض أوضح</small></div><div><span className="proof-icon"><MessageCircle size={18}/></span><b>Checkout</b><small>شك أقل</small></div><div><span className="proof-icon"><Truck size={18}/></span><b>Operations</b><small>طلبات لا تضيع</small></div><div><span className="proof-icon"><BarChart3 size={18}/></span><b>Growth</b><small>قرارات قابلة للقياس</small></div></section>
      <section className="section intro shell reveal"><div className="section-kicker">المشكلة الحقيقية</div><div><h2>المنتج مش دايمًا هو المشكلة.</h2><p>ممكن يكون عندك منتج كويس وناس مهتمة، لكن الطلب يضيع لأن الـCatalog مش واضح، الموبايل بطيء، الـCheckout مش مطمّن، الـCOD عشوائي، أو مفيش Tracking تعرف منه أين الفلوس بتروح.</p><a className="under-link" href="#contact">خلينا نعرف التسريب <ArrowLeft size={16}/></a></div></section>
      <section className="section shell reveal" id="services"><div className="section-head"><div><div className="section-kicker">بنشتغل على إيه؟</div><h2>نبني الأجزاء<br/>التي تجعل البيع <em>يشتغل.</em></h2></div><p>لا نبدأ بقائمة خدمات. نبدأ بالرحلة التجارية ونصلح الجزء الذي يمنع الطلب من الوصول أو التكرار.</p></div><div className="service-list">{services.map(([t,d,n])=><article className="service" key={n}><span className="service-number">{n}</span><div><h3>{t}</h3><p>{d}</p></div><ArrowUpLeft size={22}/></article>)}</div></section>
      <section className="section packages-section reveal" id="packages"><div className="shell"><div className="section-head"><div><div className="section-kicker lime">اختار نقطة البداية</div><h2>مش كل براند<br/>محتاج نفس <em>الحل.</em></h2></div><p>باقاتنا تبدأ من التشخيص وتكبر مع احتياج التجارة. كل واحدة لها نطاق واضح، ومفيش وعود مخفية أو تنفيذ مفتوح.</p></div><div className="offer-grid">{sitePackages.map((p,index)=><article className={p.featured?'offer-card featured':'offer-card'} key={p.id}><div className="offer-top"><span>0{index+1} / {p.platform}</span><b>{p.label}</b></div><h3>{p.name}</h3><p className="offer-price">{p.price.toLocaleString('ar-EG')} <small>{p.id==='growth-loop'?'جنيه / شهر':'جنيه / مرة'}</small></p><ul>{p.items.map(item=><li key={item}><Check size={15}/>{item}</li>)}</ul><button type="button" className="offer-link" onClick={()=>{setSelectedSite(p.id);document.querySelector('#contact')?.scrollIntoView({behavior:'smooth'})}}>ابدأ من هنا <ArrowLeft size={16}/></button></article>)}</div><div className="offer-cta"><div><b>مش عارف تبدأ منين؟</b><span>اعمل الـCommerce Diagnostic وخد اتجاه أولي يناسب حالتك.</span></div><a className="button lime-button" href="#diagnostic">ابدأ التشخيص <Sparkles size={17}/></a></div><p className="package-note">* الأسعار Starting From بالجنيه المصري. لا تشمل الدومين، الاستضافة، اشتراكات المنصات، رسوم الدفع والشحن، الإعلانات، أو الأعمال خارج النطاق.</p></div></section>
      <section className="section shell reveal" id="process"><div className="section-kicker">الطريقة</div><div className="section-head process-head"><h2>من التسريب<br/>إلى <em>النمو.</em></h2><p>كل مشروع له نقطة بداية ونطاق ومسؤوليات واضحة. هذا يقلل الـScope Creep ويخلي الإطلاق خطوة قابلة للإدارة.</p></div><div className="steps">{process.map(([n,t,d])=><div className="step" key={n}><span>{n}</span><h3>{t}</h3><p>{d}</p></div>)}</div></section>
      <section className="section dark proof-section reveal"><div className="shell"><div className="section-head"><div><div className="section-kicker lime">مش بنبيع منصة</div><h2>بنبيع طريقة<br/>تشغيل <em>أوضح.</em></h2></div><p>اختيار المنصة يأتي بعد فهم طريقة البيع، الدفع، الشحن، المحتوى، والبيانات. عشان كده ممكن نشتغل على WordPress/WooCommerce أو Shopify أو Zid أو غيرهم حسب الحالة.</p></div><div className="platforms"><span>WooCommerce</span><span>Shopify</span><span>Zid</span><span>GA4</span><span>Meta Pixel</span><span>WhatsApp</span></div><div className="industry-row"><div><small>مناسب لـ</small><strong>D2C Brands</strong></div><div><small>وكمان</small><strong>Retail & Omnichannel</strong></div><div><small>وحالات مختارة</small><strong>Clinics · B2B · Services</strong></div></div></div></section>
      <section className="section portfolio-section shell reveal" id="portfolio"><div className="section-head"><div><div className="section-kicker">Selected work</div><h2>شغل يتشاف،<br/>مش كلام <em>يتقال.</em></h2></div><p>اسحب بين المشاريع أو افتح صفحة الأعمال كاملة. كل مشروع له صورة، سياق، وBrief مختصر.</p></div><PortfolioSlider compact/><div className="portfolio-foot"><span>{projects.length} مشاريع مختارة من Ecommerce وCorporate وLanding Pages وEditorial.</span><a className="under-link" href="/portfolio">افتح صفحة كل الأعمال <ArrowLeft size={16}/></a></div></section>
      <section className="section diagnostic-section shell reveal" id="diagnostic"><div className="diagnostic-layout"><div><div className="section-kicker lime">FIND THE LEAK</div><h2>جاوب 4 أسئلة،<br/>وخد أول <em>اتجاه.</em></h2><p>مش تشخيص نهائي، لكنه بداية أذكى من عرض عام. نفهم القناة، المرحلة، الكتالوج، وأكبر نقطة احتكاك.</p><div className="diagnostic-note"><CircleCheck size={17}/> النتيجة الأولية تروح مع الـBrief لفريق CartMakers.</div></div><CommerceDiagnostic onComplete={setDiagnosticResult}/></div></section>
      <section className="section shell reveal" id="faq"><div className="section-head"><div><div className="section-kicker">أسئلة طبيعية</div><h2>قبل ما<br/>نبدأ.</h2></div><p>لو السؤال مش موجود هنا، اسأله في أول مكالمة. الوضوح جزء من الخدمة.</p></div><div className="faq-list">{faqs.map(([q,a],i)=><div className={openFaq===i?'faq open':'faq'} key={q}><button onClick={()=>setOpenFaq(openFaq===i?-1:i)}><span>{q}</span><ChevronDown size={19}/></button>{openFaq===i&&<p>{a}</p>}</div>)}</div></section>
      <section className="section contact shell" id="contact"><div className="contact-copy"><div className="section-kicker">نتكلم في التجارة</div><h2>قولنا فين واقف،<br/><em>ونبدأ صح.</em></h2><p>مش هنبعتلك عرض عام. ابعت تفاصيل بسيطة، ونرجعلك بالخطوة المناسبة: تشخيص، Launch، أو نرشحلك ما تبدأش دلوقتي.</p><div className="contact-note"><CircleCheck size={18}/> بدون وعود وهمية. بتشخيص مفيد أولًا.</div></div><form className="contact-form" onSubmit={submit}>{sent?<div className="success"><CircleCheck size={34}/><h3>وصلنا الـBrief.</h3><p>شكرًا — فريق CartMakers هيراجع التفاصيل ويتواصل معاك.</p></div>:<><label>الاسم<input name="name" required minLength="2" maxLength="100" autoComplete="name" placeholder="اسمك"/></label><label>البريد الإلكتروني<input name="email" type="email" required maxLength="160" autoComplete="email" placeholder="you@company.com"/></label><label>اسم البراند أو الشركة<input name="company" maxLength="160" autoComplete="organization" placeholder="اسم البراند"/></label><label>إيه اللي محتاج يتصلح؟<textarea name="message" required minLength="10" maxLength="3000" rows="4" placeholder="متجر، Checkout، COD، Tracking، أو مشروع جديد..."/></label><div className="form-trap" aria-hidden="true"><label>Website<input name="website" tabIndex="-1" autoComplete="off"/></label></div>{error&&<p className="form-error" role="alert">{error}</p>}<button className="button primary submit" disabled={busy}>{busy?'جاري الإرسال...':'ابعت الـBrief'} <ArrowLeft size={18}/></button></>}</form></section>
    </main><div className="sticky-cta"><a href="#diagnostic"><Sparkles size={16}/> احجز التشخيص</a><a href="#contact" aria-label="افتح نموذج التواصل"><MessageCircle size={17}/></a></div><footer className="footer shell"><a className="brand footer-brand" href="#top"><img className="brand-logo" src="/assets/cartmakers-primary-light.svg" alt="CartMakers — Ecommerce Systems & Growth"/></a><span>Ecommerce Systems & Growth</span><span>© 2026 CartMakers</span></footer>
  </div>
}
createRoot(document.getElementById('root')).render(<App/>);
